apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: my-nginx
    image: alpine 
    volumeMounts:
      - name: blobdisk01
        mountPath: /mnt/blobdiskf
  volumes:
  - name: blobdisk01
    persistanceVolumeClaim:
      claimName: pv-dd-account-hdd-5g