apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: my-nginx
    command: ["sleep"]
    args: ["100000"]
    image: docker
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.socexit
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket